// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HelloTorontoAPI.Models
{
    public partial class Post
    {
        public Post()
        {
            Comment = new HashSet<Comment>();
            PostLike = new HashSet<PostLike>();
        }

        public int PostId { get; set; }
        public string Title { get; set; }
        public string Contents { get; set; }
        public int CategoryId { get; set; }
        public DateTime PostedDt { get; set; }
        public int UserId { get; set; }

        public virtual Category Category { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual ICollection<PostLike> PostLike { get; set; }
    }
}